name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PureScript toolchain
        uses: purescript-contrib/setup-purescript@0.13.8

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output
      - name: Set up Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Purescript dependencies
        run: spago install

      - name: Build the project
        run: spago build

      - name: Run tests
        run: spago test